controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true

# Route HomeController
app_home:
    path: /home
    controller: App\Controller\HomeController::index

# Route SecurityController
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# Route RegistrationController
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Route UserController
user_list:
    path: /user/list
    controller: App\Controller\UserController::list
    methods:  [GET]

user_detail:
    path: /user/{id}
    controller: App\Controller\UserController::detail
    methods: [GET]

user_edit:
    path: /user/edit/{id}
    controller: App\Controller\UserController::edit
    methods: [GET, POST]

user_delete:
    path: /user/{id}/delete
    controller: App\Controller\UserController::delete
    methods: [POST]

# Route CommissionController
commission_new:
    path: /commission/new
    controller: App\Controller\CommissionController::new
    methods:  [GET,POST]

commission_list:
    path:     /commission/list
    controller: App\Controller\CommissionController::list
    methods:  [GET]

commission_success:
    path:     /commission/success
    controller: App\Controller\CommissionController::success
    methods:  [GET]

commission_delete: 
    path: /{id}/delete
    controller: App\Controller\CommissionController::delete
    methods: [POST]

commission_chat:
    path: /commission/chat/{id}
    controller: App\Controller\CommissionController::chat
